#!/bin/bash

sed -i 's/user  nginx;/user nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen 8080;/' /etc/nginx/sites-available/default.conf

# Restart Nginx to apply the changes
nginx -s reload
